version: 2
updates:
  - package-ecosystem: npm
    directory: /packaging/npm
    schedule:
      interval: daily
    commit-message:
      prefix: '⬆️ '
      # prefix: 'chore: '
    target-branch: develop
