version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: freebsd
        goarch: 386

archives:
  - id: ccoco
    format: binary
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}MacOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
  - id: ccoco-gz
    format: gz
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}MacOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^📝'
      - '^🤡'
      - '^🧪'
      - '^✅'
      - '^🚧'
      - '^🔨'
      - '^🔧'
      - '^🧑‍💻'
      - '^👷'
      - '^💚'
      - '^🔥'
      - '^👥'
      - '^🔖'
      - '^🔀'
      - '^🙈'
      - '^🚚'
      - '^Merge'
      - '^🎨'
      # TODO: Add more filters here
